### ISSUE TITLE
Repo name no longer reflects what this is for.

### ISSUE THREAD

**Issue by trickeydan** [sourcebots/servo-firmware#23]
As we are switching to v4 Servo Boards this year, the name of this firmware no longer reflects it's purpose.

Possible alternatives:

- `sbduino-fw`
- `arduino-fw` (We already have a repo named this)
- `uno-fw`

**Comment by RealOrangeOne** [comment]
The repo name never actually reflected its actual use. It doesn't contain firmware used in servos.

I think this links back to the wider discussion of "Should we remove the servo functionality because for Smallpeice 2019, we're shipping SR V4 servo boards", to which I think the answer is no. 

`arduino-fw` feels like a reasonable name to me, as it's accurate in both the SP2019 usage (simply as an external GPIO board), and previous iterations (as a servo controller).

**Comment by kierdavis** [comment]
:+1: for `arduino-fw`.

I don't know why https://github.com/sourcebots/arduino-fw is still hanging around, it was never used and has only created confusion (to the extent that in the past we've had volunteers implement entire features before discovering that they had been working on entirely the wrong codebase).

**Comment by trickeydan** [comment]
> I think this links back to the wider discussion of "Should we remove the servo functionality because for Smallpeice 2019, we're shipping SR V4 servo boards", to which I think the answer is no.

I've tested without a servo hat, and the errors seem to disappear within the Adafruit library. i.e there are no obvious errors if a servo command is sent.

I'm going to rename the old firmware to `legacy-arduino-fw` and this repo to `arduino-fw`.

**Comment by kierdavis** [comment]
This has now been fixed.
